### ISSUE TITLE
Metadata fetching is performed on the UI thread

### ISSUE THREAD

**Issue by Codom** [isenseDev/AppVis#1]
Whenever the app makes a request for metadata, the request is processed on the UI thread making 
any app that changes the project id manually completely unresponsive to the user while the projects is waiting for a response from iSense.

**Comment by fgmart-zz** [comment]
Chris can you explain more about what you mean by the app making a "request for metadata"?

**Comment by Codom** [comment]
I have some block functions that request metadata attached to the given project ID (ProjectName ProjectAuthor GetFieldsList etc.)
